[project]
name = "etl-binance-back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiokafka>=0.12.0",
    "fastapi[standard]>=0.116.1",
    "kafka-python>=2.2.15",
    "uvicorn>=0.35.0",
    "websockets>=15.0.1",
]
